apiRules:
  - exclude:
      uidRegex: Sample
  - exclude:
      uidRegex: SimpleViewer
  - exclude:
      uidRegex: RokuroCamera
  - exclude:
      uidRegex: DevOnly
  - include:
      uidRegex: ^VRM$
  - include:
      uidRegex: ^VRM\.
  - exclude:
      uidRegex: ^UniGLTF\.(Extensions|Animation|EditorSettingsValidator|JsonSchema|M17N|MeshUtility|ShaderPropExporter|UniUnlit)\.
  - include:
      uidRegex: ^UniGLTF$
  - include:
      uidRegex: ^UniGLTF\.
  - exclude:
      uidRegex: ^.*$
